Override or add configuration options in values input
lablabs/terraform-aws-eks-ingress-nginx pull request #2
Opened 2021-08-17 11:13 UTC by Thumbiceq

Changes:
* Add ability to override or add configuration options in default values 
* Delegate Kubernetes namespace creation to helm provider from Kubernetes provider
* Remove fake dependency variable in favor of terraform built-in module dependency
* Bump default chart version to the 3.35.0

Breaking changes:
* Removes fake dependency variable `mod_dependency` in favor of terraform built-in module dependency injection

Signed-off-by: Ondřej Šmalec <ondrej.smalec@lablabs.io>

2021-08-17 11:33 UTC, Thumbiceq commented
Tested against running cluster. Helm chart deployed and validated

2021-08-18 17:42 UTC, dojci requested changes

2021-08-18 17:42 UTC, dojci commented on main.tf
> +      "clusterName" : var.cluster_name
I don't think this values are for ingress-nginx helm chart, see possible values [here](https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx).

2021-08-18 17:42 UTC, dojci commented on main.tf
>  data "aws_region" "current" {}
Please remove unused region data source

2021-08-18 17:42 UTC, dojci commented on main.tf
> +}
We don't need deep merge data source because overriding default chart values aren't necessary (right now there is no use case)

2021-08-18 17:42 UTC, dojci commented on main.tf
> +    data.utils_deep_merge_yaml.values[0].output
We can use direct variable input instead of merging

2021-08-18 17:42 UTC, dojci commented on versions.tf
> +    }
where is this provider used?

2021-08-18 17:42 UTC, dojci commented on versions.tf
> +      version = ">= 0.12.0"
As I wrote in previous comments we don't need to override values in this module.

2021-08-19 08:54 UTC, dojci approved these changes
LGTM

2021-08-19 08:59 UTC, merged